### ISSUE TITLE
Reset Safari.sh is incomplete

### ISSUE THREAD

**Issue by dotsumae** [palantir/mac-jamf#1]
I recently had issues with safari unsuccessfully importing firefox history and favorites. It thought those files were last used january 1st 4001. After googling I noticed this was a common issue. The lines that saved me were : 
```bash
rm ~/Library/Preferences/com.apple.Safari.plistls #This one seems to be already present in your script
defaults delete com.apple.Safari
```
Those should be added to the Reset Safari.sh.
EDIT : [source](https://discussions.apple.com/thread/6670992).

**Comment by mpanighetti** [comment]
Thanks for flagging. The script already unloads and deletes the user's Safari plist (effectively the same result as the second line in your example), but I'll add the .plistls file to scope to be thorough.
